#!/usr/bin/env bash
# Shared environment setup for all training scripts in this repo.
# Source this file at the top of every entry-point script.

set -euo pipefail

# Locate project paths.
GEAR_ROOT="${GEAR_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

# PYTHONPATH: project root so `treetune` and `guidance` packages resolve.
export PYTHONPATH="${GEAR_ROOT}:${PYTHONPATH:-}"

# Jsonnet `import` resolves under the unified configs/ tree.
export APP_JSONNET_PATH="${GEAR_ROOT}/configs:${GEAR_ROOT}"

# Standard env vars (kept compatible with upstream SPO conventions).
export APP_SEED="${APP_SEED:-42}"
export APP_DISABLE_FLASH_ATTENTION="${APP_DISABLE_FLASH_ATTENTION:-${DISABLE_FLASH_ATTENTION:-0}}"
export MASTER_PORT="${MASTER_PORT:-$(python3 -c "import socket; s=socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.bind(('', 0)); print(s.getsockname()[1]); s.close()")}"
export APP_DIRECTORY="${APP_DIRECTORY:-${GEAR_ROOT}/experiments}"
export APP_MINIMIZE_STORED_FILES="${APP_MINIMIZE_STORED_FILES:-True}"
export WANDB_PROJECT="${WANDB_PROJECT:-treetune}"
mkdir -p "${APP_DIRECTORY}"

# Default GPU is index 0; override with GEAR_GPU=N or GEAR_GPUS=0,1,2,3.
# With GEAR_GPUS, Deepspeed launches one process per listed GPU.  Episode
# generation is sharded by process, so each rank can host its own vLLM server.
GEAR_GPU_INCLUDE="${GEAR_GPUS:-${GEAR_GPU:-0}}"
GEAR_FIRST_GPU="${GEAR_GPU_INCLUDE%%,*}"

# Helpers ---------------------------------------------------------------------
jsonnet_value() {
  local value="$1"
  case "${value}" in
    auto)
      echo "'auto'"
      ;;
    true|false|null)
      echo "${value}"
      ;;
    *)
      echo "${value}"
      ;;
  esac
}

ensure_gpu_config() {
  local first_gpu="$1"
  local eval_gpu="${GEAR_EVALUATE_GPU:-${first_gpu}}"
  local vllm_gpu_offset="${GEAR_VLLM_GPU_OFFSET:-${first_gpu}}"
  local gen_dir="${APP_DIRECTORY}/_generated_configs/gpus"
  local out="${gen_dir}/gpu_${first_gpu}_eval_${eval_gpu}_vllm_offset_${vllm_gpu_offset}.jsonnet"

  mkdir -p "${gen_dir}"
  cat > "${out}" <<EOF
// Auto-generated by scripts/_common.sh:ensure_gpu_config.
// Deepspeed include: localhost:${GEAR_GPU_INCLUDE}
// Set GEAR_VLLM_GPU_OFFSET to put generation vLLM servers on another GPU block.
{
  evaluate_gpu: ${eval_gpu},
  episode_generator+: {
    gpu_offset: ${vllm_gpu_offset},
  },
}
EOF
  echo "${out}"
}

ensure_runtime_config() {
  if [[ "${GEAR_FAST_OVERLAY:-1}" == "0" ]]; then
    return 0
  fi

  local gen_dir="${APP_DIRECTORY}/_generated_configs/runtime_overrides"
  local out="${gen_dir}/short_run_fast_runtime.jsonnet"

  local eval_every="${GEAR_EVAL_EVERY_N_ITERATIONS:-10}"
  local save_steps="${GEAR_SAVE_STEPS:-10}"
  local keep_steps="${GEAR_CHECKPOINT_KEEP_STEPS:-1}"
  local kl_coef="${GEAR_KL_COEF:-0.0}"
  local target_train_batch_size="${GEAR_TARGET_TRAIN_BATCH_SIZE:-128}"
  local gradient_accumulation_steps="${GEAR_GRADIENT_ACCUMULATION_STEPS:-null}"
  local per_device_train_batch_size="${GEAR_PER_DEVICE_TRAIN_BATCH_SIZE:-2}"
  if [[ "${gradient_accumulation_steps}" != "null" && -z "${GEAR_PER_DEVICE_TRAIN_BATCH_SIZE:-}" ]]; then
    per_device_train_batch_size="null"
  fi
  local per_device_eval_batch_size="${GEAR_PER_DEVICE_EVAL_BATCH_SIZE:-2}"
  local num_epochs_per_iteration="${GEAR_NUM_EPOCHS_PER_ITERATION:-1}"
  local num_episodes_per_iteration="${GEAR_NUM_EPISODES_PER_ITERATION:-null}"
  local dataset_num_samples_per_iteration="${GEAR_DATASET_NUM_SAMPLES_PER_ITERATION:-null}"
  local total_num_iterations="${GEAR_TOTAL_NUM_ITERATIONS:-null}"
  local vllm_gpu_mem
  vllm_gpu_mem="$(jsonnet_value "${GEAR_VLLM_GPU_MEMORY_UTILIZATION:-auto}")"
  local vllm_min_free="${GEAR_VLLM_MIN_AVAILABLE_GPU_MEMORY_MB:-1024}"
  local max_programs="${GEAR_MAX_CONCURRENT_PROGRAMS:-256}"
  local max_generations="${GEAR_MAX_CONCURRENT_GENERATIONS:-256}"
  local value_max_programs="${GEAR_VALUE_MAX_CONCURRENT_PROGRAMS:-512}"
  local value_max_generations="${GEAR_VALUE_MAX_CONCURRENT_GENERATIONS:-512}"
  local vllm_max_num_seqs="${GEAR_VLLM_MAX_NUM_SEQS:-1024}"
  local vllm_swap_space="${GEAR_VLLM_SWAP_SPACE:-null}"
  local gear_inference_overrides=""
  local gear_episode_overrides=""
  if [[ -n "${GEAR_SCORE_CONCURRENCY:-}" ]]; then
    gear_inference_overrides+="      gear_score_concurrency: ${GEAR_SCORE_CONCURRENCY},"$'\n'
  fi
  if [[ -n "${EPS_TAIL_CALIBRATION_PATH:-}" ]]; then
    gear_inference_overrides+="      gear_eps_tail_calibration_path: '${EPS_TAIL_CALIBRATION_PATH}',"$'\n'
  fi
  if [[ -n "${GEAR_K_ALGORITHM:-}" ]]; then
    gear_inference_overrides+="      gear_k_algorithm: '${GEAR_K_ALGORITHM}',"$'\n'
  fi
  if [[ -n "${GEAR_GENERATION_MODE:-}" ]]; then
    gear_inference_overrides+="      gear_generation_mode: '${GEAR_GENERATION_MODE}',"$'\n'
  fi
  if [[ -n "${GEAR_PILOT_BRANCH_FACTOR:-}" ]]; then
    gear_inference_overrides+="      gear_pilot_branch_factor: ${GEAR_PILOT_BRANCH_FACTOR},"$'\n'
  fi
  if [[ -n "${GEAR_LIKELIHOOD_SAMPLES_PER_DISTRIBUTION:-}" ]]; then
    gear_inference_overrides+="      gear_likelihood_samples_per_distribution: ${GEAR_LIKELIHOOD_SAMPLES_PER_DISTRIBUTION},"$'\n'
  fi
  if [[ -n "${GEAR_TV_SUBNODE_MAX_TOKENS:-}" ]]; then
    gear_inference_overrides+="      gear_tv_subnode_max_tokens: ${GEAR_TV_SUBNODE_MAX_TOKENS},"$'\n'
  fi
  if [[ -n "${GEAR_TV_SECOND_PHASE_TOKENS:-}" ]]; then
    gear_inference_overrides+="      gear_tv_second_phase_tokens: ${GEAR_TV_SECOND_PHASE_TOKENS},"$'\n'
  fi
  if [[ -n "${GEAR_BUDGET_OVERHEAD_MODE:-}" ]]; then
    gear_inference_overrides+="      gear_budget_overhead_mode: '${GEAR_BUDGET_OVERHEAD_MODE}',"$'\n'
  fi
  if [[ -n "${GEAR_ALLOCATION_MODE:-}" ]]; then
    gear_inference_overrides+="      gear_allocation_mode: '${GEAR_ALLOCATION_MODE}',"$'\n'
  fi
  if [[ -n "${GEAR_USE_RESIDUAL_BUDGET:-}" ]]; then
    gear_inference_overrides+="      gear_use_residual_budget: $(jsonnet_value "${GEAR_USE_RESIDUAL_BUDGET}"),"$'\n'
  fi
  if [[ -n "${GEAR_N_MIN:-}" ]]; then
    gear_inference_overrides+="      gear_n_min: ${GEAR_N_MIN},"$'\n'
  fi
  if [[ -n "${GEAR_BUDGET_QUEUE_COUNT:-}" ]]; then
    gear_inference_overrides+="      gear_budget_queue_count: ${GEAR_BUDGET_QUEUE_COUNT},"$'\n'
  fi
  if [[ -n "${GEAR_SKIP_NEAR_LEAF_EXPAND:-}" ]]; then
    gear_inference_overrides+="      gear_skip_near_leaf_expand: $(jsonnet_value "${GEAR_SKIP_NEAR_LEAF_EXPAND}"),"$'\n'
  fi
  if [[ -n "${GEAR_ROOT_ALLOCATION:-}" ]]; then
    gear_inference_overrides+="      gear_root_allocation: $(jsonnet_value "${GEAR_ROOT_ALLOCATION}"),"$'\n'
  fi
  if [[ -n "${GEAR_TREE_UPDATE_MODE:-}" ]]; then
    gear_episode_overrides+="    tree_update_mode: '${GEAR_TREE_UPDATE_MODE}',"$'\n'
  fi
  if [[ -n "${GEAR_TREEPO_GLOBAL_WEIGHT:-}" ]]; then
    gear_episode_overrides+="    treepo_global_weight: ${GEAR_TREEPO_GLOBAL_WEIGHT},"$'\n'
  fi
  if [[ -n "${GEAR_TREERL_GAMMA:-}" ]]; then
    gear_episode_overrides+="    treerl_gamma: ${GEAR_TREERL_GAMMA},"$'\n'
  fi

  mkdir -p "${gen_dir}"
  cat > "${out}" <<EOF
// Auto-generated by scripts/_common.sh:ensure_runtime_config.
// Short-run defaults favor throughput and checkpoint resumability.
// Disable this overlay with GEAR_FAST_OVERLAY=0.
// Speed-related env vars:
//   GEAR_GPUS=0,1,2,3
//   GEAR_VLLM_GPU_OFFSET=4
//   GEAR_KL_COEF=${kl_coef}
//   GEAR_TARGET_TRAIN_BATCH_SIZE=${target_train_batch_size}
//   GEAR_PER_DEVICE_TRAIN_BATCH_SIZE=${per_device_train_batch_size}
//   GEAR_GRADIENT_ACCUMULATION_STEPS=${gradient_accumulation_steps}
//   GEAR_NUM_EPISODES_PER_ITERATION=${num_episodes_per_iteration}
//   GEAR_DATASET_NUM_SAMPLES_PER_ITERATION=${dataset_num_samples_per_iteration}
//   GEAR_MAX_CONCURRENT_PROGRAMS=${max_programs}
//   GEAR_MAX_CONCURRENT_GENERATIONS=${max_generations}
//   GEAR_SCORE_CONCURRENCY=${GEAR_SCORE_CONCURRENCY:-model default}
//   GEAR_VLLM_GPU_MEMORY_UTILIZATION=${GEAR_VLLM_GPU_MEMORY_UTILIZATION:-auto}
//   GEAR_VLLM_SWAP_SPACE=${vllm_swap_space}  // null by default for newer vLLM
{
  evaluate_every_n_iterations: ${eval_every},
  num_episodes_per_iteration: if ${num_episodes_per_iteration} == null then super.num_episodes_per_iteration else ${num_episodes_per_iteration},
  num_iterations: if ${total_num_iterations} == null then super.num_iterations else ${total_num_iterations},
  episode_generator+: {
${gear_episode_overrides}    dataset_num_samples_per_iteration: if ${dataset_num_samples_per_iteration} == null then super.dataset_num_samples_per_iteration else ${dataset_num_samples_per_iteration},
    total_num_iterations: if ${total_num_iterations} == null then super.total_num_iterations else ${total_num_iterations},
    vllm_gpu_memory_utilization: ${vllm_gpu_mem},
    vllm_min_available_gpu_memory_mb: ${vllm_min_free},
    inference_strategy+: {
      max_concurrent_programs: ${max_programs},
      max_concurrent_generations: ${max_generations},
${gear_inference_overrides}    },
    value_estimation_inference_strategy+: {
      max_concurrent_programs: ${value_max_programs},
      max_concurrent_generations: ${value_max_generations},
    },
    vllm_server+: {
      swap_space: ${vllm_swap_space},
      max_num_seqs: ${vllm_max_num_seqs},
      enable_prefix_caching: true,
    },
  },
  trainer+: {
    params+: {
      init_kl_coef: ${kl_coef},
    },
    num_epochs_per_iteration: ${num_epochs_per_iteration},
    general_training_args+: {
      target_train_batch_size: ${target_train_batch_size},
      per_device_train_batch_size: ${per_device_train_batch_size},
      per_device_eval_batch_size: ${per_device_eval_batch_size},
      gradient_accumulation_steps: ${gradient_accumulation_steps},
      save_steps: ${save_steps},
      checkpoint_keep_steps: ${keep_steps},
    },
  },
}
EOF
  echo "${out}"
}

# Run training with `--configs A,B,C`.  Algorithm selection is purely from the
# chained configs; the unified entry point is `treetune.main` (GEAR is
# auto-registered when `treetune` is imported).
#
# Usage: gear_run "<exp_name>" "configs/foo.jsonnet,configs/bar.jsonnet" [extra args]
gear_run() {
  local exp_name="$1"; shift
  local cfgs="$1"; shift
  local no_sample_replacement_config gpu_config runtime_config resolved_cfgs
  no_sample_replacement_config="${GEAR_ROOT}/configs/episode_generators/noSamplRplc.jsonnet"
  gpu_config="$(ensure_gpu_config "${GEAR_FIRST_GPU}")"
  runtime_config="$(ensure_runtime_config)"
  resolved_cfgs="${cfgs}"
  if [[ ",${resolved_cfgs}," != *",${no_sample_replacement_config},"* ]]; then
    resolved_cfgs+=",${no_sample_replacement_config}"
  fi
  resolved_cfgs+=",${gpu_config}"
  if [[ -n "${runtime_config}" ]]; then
    resolved_cfgs+=",${runtime_config}"
  fi
  WANDB_PROJECT="${WANDB_PROJECT}" \
  APP_EXPERIMENT_NAME="${exp_name}" \
  deepspeed --master_port "${MASTER_PORT}" --include "localhost:${GEAR_GPU_INCLUDE}" \
    "${GEAR_ROOT}/treetune/main.py" \
    --configs "${resolved_cfgs}" \
    "$@" \
    run_iteration_loop
}

gear_eval() {
  local exp_name="$1"; shift
  local cfgs="$1"; shift
  local last_policy="$1"; shift
  local gpu_config
  gpu_config="$(ensure_gpu_config "${GEAR_FIRST_GPU}")"
  WANDB_PROJECT="${WANDB_PROJECT}" \
  APP_EXPERIMENT_NAME="${exp_name}" \
  deepspeed --master_port "${MASTER_PORT}" --include "localhost:${GEAR_GPU_INCLUDE}" \
    "${GEAR_ROOT}/treetune/main.py" \
    --configs "${cfgs},${gpu_config}" \
    "$@" \
    evaluate --iteration 0 --last_policy_path "${last_policy}"
}

# ensure_tree_config <shape>
# Resolve a tree shape (e.g. "666", "6666", "3456", "8888") to a jsonnet
# overlay path.  If a checked-in config exists unde
#   configs/episode_generators/branch_factor_<shape>.jsonnet
# we use it as-is.  Otherwise we auto-generate one unde
#   configs/episode_generators/_generated/branch_factor_<shape>.jsonnet
# so any shape works without hand-editing the repo.
#
# Shape is a string of digits 1-9, one digit per depth level (the i-th
# digit is the branch factor at depth i).  Generated configs use an M
# (per-segment token cap) default by depth: <=3 -> 600, 4 -> 500, 5 -> 400,
# >=6 -> 300.  TREE_M=<positive-int> is appended as a final overlay so it also
# overrides checked-in and previously generated configs.
#
# Prints one config path, or a comma-separated config list when TREE_M is set.
ensure_tree_config() {
  local shape="$1"
  local checked_in="${GEAR_ROOT}/configs/episode_generators/branch_factor_${shape}.jsonnet"
  local tree_config

  if [[ -f "${checked_in}" ]]; then
    tree_config="${checked_in}"
  else
    if ! [[ "${shape}" =~ ^[1-9]+$ ]]; then
      echo "[tree] invalid tree shape '${shape}': must be a string of digits 1-9 (e.g. 666, 3456)" >&2
      return 1
    fi

    local gen_dir="${GEAR_ROOT}/configs/episode_generators/_generated"
    local out="${gen_dir}/branch_factor_${shape}.jsonnet"
    local depth=${#shape}
    local M
    if   [[ ${depth} -le 3 ]]; then M=600
    elif [[ ${depth} -eq 4 ]]; then M=500
    elif [[ ${depth} -eq 5 ]]; then M=400
    else                            M=300
    fi

    if [[ ! -f "${out}" ]]; then
      mkdir -p "${gen_dir}"
      {
        echo "// Auto-generated by scripts/_common.sh:ensure_tree_config."
        echo "// Shape='${shape}' depth=${depth} M=${M}."
        echo "{"
        echo "  episode_generator+: {"
        echo "    inference_strategy+: {"
        echo "      M: ${M},"
        echo "      max_depth: ${depth},"
        echo "      branch_factor_strategy+: {"
        echo "        branch_factors: ["
        local i
        for (( i=0; i<depth; i++ )); do
          echo "          { depth: ${i}, branch_factor: ${shape:$i:1} },"
        done
        echo "        ],"
        echo "      },"
        echo "    },"
        echo "  },"
        echo "}"
      } > "${out}"

      echo "[tree] generated branch_factor_${shape}.jsonnet (depth=${depth}, M=${M})" >&2
    fi
    tree_config="${out}"
  fi

  if [[ -z "${TREE_M:-}" ]]; then
    echo "${tree_config}"
    return 0
  fi

  if ! [[ "${TREE_M}" =~ ^[1-9][0-9]*$ ]]; then
    echo "[tree] invalid TREE_M='${TREE_M}': must be a positive integer" >&2
    return 1
  fi

  local m_gen_dir="${APP_DIRECTORY}/_generated_configs/tree_overrides"
  local m_override="${m_gen_dir}/tree_M_${TREE_M}.jsonnet"
  mkdir -p "${m_gen_dir}"
  cat > "${m_override}" <<EOF
// Auto-generated by scripts/_common.sh:ensure_tree_config.
{
  episode_generator+: {
    inference_strategy+: {
      M: ${TREE_M},
    },
  },
}
EOF

  echo "${tree_config},${m_override}"
}

default_model_base_for_suffix() {
  local suffix="$1"
  case "${suffix}" in
    gear_tree|spo_tree|spo_chain|grpo)
      echo "qwen1_5b_base"
      ;;
    ppo|dpo_positive|restem)
      echo "rho1bSft2"
      ;;
    *)
      echo "qwen1_5b_base"
      ;;
  esac
}

# resolve_math_config <suffix> <model_alias>
# First prefer a fully materialized config:
#   configs/polIter_<model_alias>_<suffix>_MATH.jsonnet
# If it does not exist but configs/model_overrides/<model_alias>.jsonnet does,
# compose a known base config with that model override. This keeps new model
# support compact while preserving existing hand-tuned configs.
resolve_math_config() {
  local suffix="$1"
  local model="$2"
  local direct="${GEAR_ROOT}/configs/polIter_${model}_${suffix}_MATH.jsonnet"
  if [[ -f "${direct}" ]]; then
    echo "${direct}"
    return 0
  fi

  local override="${GEAR_ROOT}/configs/model_overrides/${model}.jsonnet"
  if [[ -f "${override}" ]]; then
    local base="${MODEL_BASE:-$(default_model_base_for_suffix "${suffix}")}"
    local base_cfg="${GEAR_ROOT}/configs/polIter_${base}_${suffix}_MATH.jsonnet"
    if [[ ! -f "${base_cfg}" ]]; then
      echo "[model] missing base config for MODEL=${model}: ${base_cfg}" >&2
      return 1
    fi
    echo "${base_cfg},${override}"
    return 0
  fi

  echo "[model] unknown MODEL=${model}; expected ${direct} or ${override}" >&2
  return 1
}
